"""
remove unique constraint from symptoms.name

Revision ID: 20251029100001
Revises: 20251029100000
Create Date: 2025-10-29 10:00:01.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20251029100001'
down_revision = '20251029100000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除症狀名稱的唯一約束 (SQLite 特殊處理)
    # SQLite 不支持直接刪除唯一約束，需要重建表
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        # 由於SQLite的限制，我們不能直接刪除自動創建的唯一索引
        # 這個遷移主要目的是記錄我們已經移除了模型中的unique=True約束
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 恢復症狀名稱的唯一約束
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        # SQLite 不支持直接添加唯一約束到現有表，需要重建表
        # 這個遷移主要目的是記錄我們已經恢復了模型中的unique=True約束
        pass
    # ### end Alembic commands ###