"""
add unique constraint to symptoms.name

Revision ID: 20251029100002
Revises: 20251029100001
Create Date: 2025-10-29 10:00:02.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251029100002'
down_revision = '20251029100001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加症狀名稱的唯一約束
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_symptoms_name', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除症狀名稱的唯一約束
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.drop_constraint('uq_symptoms_name', type_='unique')
    # ### end Alembic commands ###